### ISSUE TITLE
Cors Issue - setting of cors address

### ISSUE THREAD

**Issue by willscottrod** [adrien2p/medusa-extender#178] opened 2023-02-17 04:22 UTC
### Discussed in https://github.com/adrien2p/medusa-extender/discussions/177

<div type='discussions-op-text'>

<sup>Originally posted by **willscottrod** February 17, 2023</sup>
Hi

I'm running into a cors Issue when trying to call an API route from the storefront. All other requests through the normal Medusa API are working fine (from the same url) and the endpoint is also working when just putting in the url in browser. 

Does the Medusa extender have separate cors settings I need to change? It doesn't seem to depend on the normal cors settings set in medusa-config. I can't see anything in the documentation about this as well.

Any help would be appreciated.</div>

**Comment by adrien2p** [comment] 2023-02-17 07:10
There is no cors issues and medusa-extender does not consume different cors configuration. 

I suggest you to start a discussion on discord as it is easier to discuss. It would be nice if you can share a reproducible repo or the piece of code that does not work.

In the meantime I close this issue.

Ps: no need to open both discussion and issue. The issue is enough. I ve removed the discussion.

**Closed** 2023-02-17 07:10 UTC
